// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Inventory struct {
	PlayerID string `json:"playerID"`
}

type Item struct {
	ItemID string `json:"itemID"`
	Name   string `json:"name"`
}

type Query struct {
}
